### ISSUE TITLE
yarn build is not stable

### ISSUE THREAD

**Issue by Naveenchandra07** [yooneskh/vite-neutralinojs-template#2]
When I launch the app using yarn dev, the app starts perfectly fine and I don't see any problems. But when I tried to create the exe using the command "yarn build" I get an exe created under dist folder but on launch off the exe it shows blank screen. I tried couple of tricks posted in google search about running the app and build commands in admin mode but no luck.
Although when I expand the window I could see the content for a short span of time like microsecs! but again it disappears. Can you pls help me to fix this problem ?

One more observation: If I try to launch the app using the command "neu run" I am seeing the same blank screen!

**Comment by yooneskh** [comment]
Hello. Sorry for delay in answering. I was busy with some things.

I am migrating the project to v3 right now and some things seem to have changed. This will hopefully be fixed soon.

**Comment by yooneskh** [comment]
@Naveenchandra07 i have upgraded the app to Neu v3 and it seems stable now. Try it and reopen this issue if it still exists for you. remember to clone this again as installation instructions have changed.
